_target_: src.model.segmentation_model.HoneyBeeModel
_recursive_: False

model_cfg:
  _target_: src.model.modules.custom_unet.Unet
  channels: [1, 64, 128, 256, 512, 1024]
  classes: 9
  encoder_name: "default"


