defaults:
  - default.yaml

# watch_model:
#   _target_: src.callbacks.wandb_callbacks.WatchModel
#   log: "all"
#   log_freq: 50

upload_code_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCodeAsArtifact
  code_dir: ${general.work_dir}/src

upload_ckpts_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCheckpointsAsArtifact
  ckpt_dir: "checkpoints/"
  upload_best_only: True

log_confusion_matrix:
  _target_: src.callbacks.wandb_callbacks.LogConfusionMatrix
  log_freq: 300

log_image_predictions:
  _target_: src.callbacks.wandb_callbacks.LogImagePredictions
  log_freq: 300