defaults:
  - default.yaml

# watch_model:
#   _target_: src.callbacks.wandb_callbacks.WatchModel
#   log: "all"
#   log_freq: 50

upload_code_as_artifact:
  _target_: src.callbacks.wandb_callbacks_cross_val.UploadCodeAsArtifact
  code_dir: ${general.work_dir}/src

upload_ckpts_as_artifact:
  _target_: src.callbacks.wandb_callbacks_cross_val.UploadCheckpointsAsArtifact
  ckpt_dir: "checkpoints/"
  upload_best_only: True

# log_f1_precision_recall_heatmap:
#   _target_: src.callbacks.wandb_callbacks_cross_val.LogF1PrecRecHeatmap

log_confusion_matrix:
  _target_: src.callbacks.wandb_callbacks_cross_val.LogConfusionMatrix
  log_freq: 300

log_image_predictions:
  _target_: src.callbacks.wandb_callbacks_cross_val.LogImagePredictions
  log_freq: 300