_target_: src.datamodule.honeybee_datamodule_cross_val.HoneyBeesDataModule
_recursive_: False

dataset_args:
  train:
    _target_: src.datamodule.datasets.custom_datasets.CustomDatasetBatchCrossVal
    crop_size: 416
    n_crops_in_batch: 16 # used with custom-dataset that generates batches in __getitem__
  val:
    _target_: src.datamodule.datasets.custom_datasets.CustomDatasetCrossVal

  test:
    _target_: src.datamodule.datasets.custom_datasets.CustomDataset
    images_path: "data/val/images"
    labels_path: "data/val/labels"

dataloader_args:
  train:
    batch_size: 16
    shuffle: False
    pin_memory: True
    num_workers: 8
    drop_last: False
  test:
    batch_size: 1
    shuffle: False
    pin_memory: False
    num_workers: 1
  val:
    batch_size: 1
    shuffle: False
    pin_memory: True
    num_workers: 1
    drop_last: False

