_target_: src.datamodule.honeybee_datamodule.HoneyBeesDataModule
_recursive_: False

dataset_args:
  train:
    _target_: src.datamodule.datasets.custom_datasets.CustomDataset
    images_path: "data/train/images"
    labels_path: "data/train/labels"
    phase: train
  val:
    _target_: src.datamodule.datasets.custom_datasets.CustomDataset
    images_path: "data/val/images"
    labels_path: "data/val/labels"
    phase: val
  test:
    _target_: src.datamodule.datasets.custom_datasets.CustomTestDataset
    images_path: "data/test/images"
    labels_path: "data/test/labels"
    phase: test

dataloader_args:
  train:
    batch_size: 2
    shuffle: False
    pin_memory: True
    num_workers: 16
    drop_last: False
  test:
    batch_size: 2
    shuffle: False
    pin_memory: False
    num_workers: 1
  val:
    batch_size: 1
    shuffle: False
    pin_memory: True
    num_workers: 2
    drop_last: False

